name: Dependency Review

on:
    pull_request:
        branches: [main]

permissions:
    contents: write
    statuses: write

jobs:
    dependency-review:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Dependency Review
              uses: actions/dependency-review-action@v4

            - name: 'notify vercel'
              uses: 'vercel/repository-dispatch/actions/status@v1'
              with:
                  name: "Vercel - dueforge: dependency-review"
